version: "3.9"

services:
  db:
    image: postgres
    volumes:
       - ./data/db:/var/lib/postgresql/data
    environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=pass123
    ports:
       - "5432:5432"   
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
       - .:/code
    ports:
       - "8001:8000"
    depends_on:
       - db 
       
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15673:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: myvhost
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass123
  worker:
        build:
          context: .
        container_name: wor01
        command: celery -A distributed_project worker -l info -f /code/celery.log 
        depends_on:
            - rabbit
            - web    
  
  
