# Generated by Django 4.0.5 on 2023-07-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('parent_url', models.TextField()),
                ('description', models.TextField()),
                ('upc', models.CharField(max_length=30, unique=True)),
                ('product_type', models.CharField(max_length=30, unique=True)),
                ('price_exclude_tax', models.FloatField()),
                ('price_include_tax', models.FloatField()),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('tax', models.FloatField()),
                ('stock', models.IntegerField()),
                ('no_reviews', models.IntegerField()),
            ],
        ),
    ]
